apiVersion: tekton.dev/v1alpha1
kind: ClusterTask
metadata:
  name: clustertask
spec:
  steps:
  - image: ubuntu
    script: |
      #!/usr/bin/env bash
      echo "Hello"
---
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: clustertask-
spec:
  taskRef:
    name: clustertask
    kind: ClusterTask
